{
 "title": "User Repository Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "User API Counter",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "user_api_counter_total", "legendFormat": "api calls" }
   ]
  },
  {
   "title": "Get User By ID Counter",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "get_user_by_id_counter_total", "legendFormat": "api calls" }
   ]
  },
  {
   "title": "Post New User Counter",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "post_new_user_counter_total", "legendFormat": "api calls" }
   ]
  },
  {
   "title": "Delete User Counter",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "delete_user_counter_total", "legendFormat": "api calls" }
   ]
  }
 ]
}