version: "3.8"
services:
  jenkins:
      image: jenkins/jenkins:lts
      container_name: jenkins
      user: root
      ports:
          - "8080:8080"
          - "50000:50000"
      volumes:
          - ./jenkins-data:/var/jenkins_home
          - //var/run/docker.sock://var/run/docker.sock
      restart: always
      networks:
          - jenkins

  sonarqube:
      image: sonarqube:latest
      container_name: sonarqube
      ports:
          - "9000:9000"
          - "9092:9092"
      volumes:
          - ./sonarqube-data:/opt/sonarqube/data
          - ./sonarqube-extensions:/opt/sonarqube/extensions
          - ./sonarqube-logs:/opt/sonarqube/logs
          - ./sonarqube-temp:/opt/sonarqube/temp
      restart: always
      networks:
          - jenkins
  
  prometheus:
      image: prom/prometheus
      container_name: prometheus
      ports:
          - "9090:9090"
      volumes:
          - ./prometheus.yml:/etc/prometheus/prometheus.yml
      restart: always
      networks:
          - jenkins
  grafana:
      image: grafana/grafana
      container_name: grafana
      ports:
          - "3000:3000"
      volumes:
          - ./grafana-data:/var/lib/grafana
      restart: always
      networks:
          - jenkins

networks:
    jenkins:
        driver: bridge
